### ISSUE TITLE
how can I  increment  counter when show picture

### ISSUE THREAD

**Issue by pajooheshgar63** [Pagawa/PgwSlideshow#3]
Hi.
I want to increment counter of image in my database when show this image.
how can I do this?

**Comment by pajooheshgar63** [comment]
Is there anybody to answer my question?

**Comment by jonathan-piat** [comment]
Hello,

Did you try to use the plugin option "afterSlide" or "beforeSlide"?
See more at http://pgwjs.com/pgwslideshow

The option contains a function in which you can call a AJAX request to increment your DB entry.

Regards,
Jonathan

**Comment by pajooheshgar63** [comment]
Hello Dear Jonathan.
I tried these plugin options but i can't run this code 
pgwSlideshow.getCurrentSlide();
this is my code:
java scriot file:
$.fn.pgwSlideshow = function(options) {

        var defaults = {
            mainClassName : 'pgwSlideshow',
            transitionEffect : 'sliding',
            displayList : true,
            displayControls : true,
            touchControls : true,
            autoSlide : false,
            beforeSlide : false,
            afterSlide : function() {  inc_img_counter(current_slid); }, // how to get the current slide????
            maxHeight : null,
            adaptiveDuration : 200,
            transitionDuration : 500,
            intervalDuration : 3000
        };
the code in html file:
var pgwSlideshow='';
$(document).ready(function() {
     pgwSlideshow = $('.pgwSlideshow').pgwSlideshow(); 

});


function inc_img_counter(current_slid)
{
   //this is for ajax
}
my problem is that I can't find the current slide.
I'd appreciate you if you help me to solve this problem
Regards.
Mohsen.

**Comment by pajooheshgar63** [comment]
Hello Jonathan.
Thank you you very much for your useful answer.
My problem solved.
Have a good time.

**Comment by jonathan-piat** [comment]
It's a great news.
Before closing this issue, I paste here a sample code to do what you wanted:

```javascipt
$('.pgwSlideshow').pgwSlideshow({
    afterSlide: function(id) {
           // The parameter "id" returns the id of the current slide
           // To increment a database, just call en AJAX request here.
    }
});
```
